name: magnumposts
description: Aplicativo de posts para o desafio Magnum Bank
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # HTTP Client
  dio: ^5.4.0

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Local Storage
  shared_preferences: ^2.2.2

  # UI Components
  cached_network_image: ^3.3.1

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true